# Generated by Django 5.0.4 on 2024-04-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthyear',
            field=models.IntegerField(default=1970),
        ),
    ]
